on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy via FTP
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://lesetraining.kloetz.com
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: List output files
        run: ls

      - name: Upload
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          local-dir: dist/
          git-ftp-args: --insecure # if your certificate is setup correctly this can be removed
